### ISSUE TITLE
Undefined Behavior sanitizer warnings on Linux

### ISSUE THREAD

**Issue by pedronavf** [Celtoys/Remotery#106]
gcc 6.2 on Linux, with Undefined Behavior Sanitizer, reports three runtime issues:

### Signed integer overflow
```
/home/pnavarro/git/nrdp/16.3/3rdparty/remotery/Remotery.c:290:51: runtime error: signed integer overflow: 1479158480 * 1000000 cannot be represented in type 'long int'
    #0 0x89fc144 in usTimer_Init /home/pnavarro/git/nrdp/16.3/3rdparty/remotery/Remotery.c:290
    #1 0x8a12f72 in Remotery_Constructor /home/pnavarro/git/nrdp/16.3/3rdparty/remotery/Remotery.c:4632
    #2 0x8a14de7 in _rmt_CreateGlobalInstance /home/pnavarro/git/nrdp/16.3/3rdparty/remotery/Remotery.c:4844
    #3 0x89db6d8 in gibbon_main /home/pnavarro/git/nrdp/16.3/src/platform/gibbon/gibbon_main.cpp:825
    #4 0x89d89a8 in main /home/pnavarro/git/nrdp/16.3/src/platform/gibbon/main.cpp:20
```

```
/home/pnavarro/git/nrdp/16.3/3rdparty/remotery/Remotery.c:316:36: runtime error: signed integer overflow: 1479158481 * 1000000 cannot be represented in type 'long int'
    #0 0x89fc31c in usTimer_Get /home/pnavarro/git/nrdp/16.3/3rdparty/remotery/Remotery.c:316
    #1 0x8a15dde in _rmt_BeginCPUSample /home/pnavarro/git/nrdp/16.3/3rdparty/remotery/Remotery.c:5050
    #2 0x8a126be in Remotery_ThreadMain /home/pnavarro/git/nrdp/16.3/3rdparty/remotery/Remotery.c:4508
    #3 0x89fcfb8 in StartFunc /home/pnavarro/git/nrdp/16.3/3rdparty/remotery/Remotery.c:916
```

### Left shift undefined behavior
```
/home/pnavarro/git/nrdp/16.3/3rdparty/remotery/Remotery.c:2615:36: runtime error: left shift of 128 by 24 places cannot be represented in type 'int'
    #0 0x8a0617f in calc /home/pnavarro/git/nrdp/16.3/3rdparty/remotery/Remotery.c:2615
    #1 0x8a066bb in SHA1_Calculate /home/pnavarro/git/nrdp/16.3/3rdparty/remotery/Remotery.c:2636
    #2 0x8a07bd6 in WebSocketHandshake /home/pnavarro/git/nrdp/16.3/3rdparty/remotery/Remotery.c:2971
    #3 0x8a08832 in WebSocket_AcceptConnection /home/pnavarro/git/nrdp/16.3/3rdparty/remotery/Remotery.c:3051
    #4 0x8a0c205 in Server_Update /home/pnavarro/git/nrdp/16.3/3rdparty/remotery/Remotery.c:3603
    #5 0x8a1272b in Remotery_ThreadMain /home/pnavarro/git/nrdp/16.3/3rdparty/remotery/Remotery.c:4511
    #6 0x89fcfa0 in StartFunc /home/pnavarro/git/nrdp/16.3/3rdparty/remotery/Remotery.c:916
    #7 0xf7276780 in asan_thread_start /home/pnavarro/crosstool/.build/src/gcc-6.2.0/libsanitizer/asan/asan_interceptors.cc:226
    #8 0xf51bb2c4 in start_thread (/lib/i386-linux-gnu/libpthread.so.0+0x62c4)
    #9 0xf40baeed in __clone (/lib/i386-linux-gnu/libc.so.6+0xe6eed)
```

**Comment by dwilliamson** [comment]
Thankyou for your checks and fixes
